# ================================
# Netplan Configuration - Ubuntu Server
# ================================
# Path: /etc/netplan/00-installer-config-STATIC.yaml
# Purpose:
# - ens33 = Internal LAN (VMnet6) → static IP
# - ens37 = NAT interface → internet (DHCP)
# ================================

# Netplan config version and renderer NetworkManager (GUI-based)
network:
  version: 2
  renderer: networkd

  ethernets:
    # Lan interface using VMnet6 - Disable DHCP for static IP - Set the IP
    ens33:
      dhcp4: no
      addresses:
        - 192.168.100.10/24
    
    # NAT interface with active DHCP auto IP from VMware NAT
    ens37:
      dhcp4: yes