# ================================
# Netplan Configuration - Ubuntu Server
# ================================
# Purpose:
# - ens33 = Internal LAN (VMnet5) → static IP
# - ens37 = NAT interface → internet (DHCP)
# ================================

# Netplan config version and renderer systemd-networkd (server style)
network:
  version: 2
  renderer: networkd

  ethernets:
    # Lan interface using VMnet5 - Disable DHCP for static IP - Set the IP
    ens33:
      dhcp4: no
      addresses:
        - 192.168.56.10/24
    
    # NAT interface with active DHCP auto IP from VMware NAT
    ens37:
      dhcp4: yes