# ================================
# Rsyslog Client Forwarding - DDP client1
# ================================
# Purpose:
# - Forward logs to server1.ddp.is
# - using port 514
# - Support centralized monitoring
# ================================

*.* @@192.168.100.10:514